### ISSUE TITLE
Socks5 Upd associate without UDPClient

### ISSUE THREAD

**Issue by mirasrael** [GreatFireWall/Socklient#2]
Hi!

As I see from code it is possible to use own UDP client with Socks5. So if I have other library (Lidgren.Network) which creates Socket internally it should be possible to obtain IPEndPoint from UdpAssociate and then use it as arguments for NetPeer constructor.

It will be very useful feature to use it as Relay with other libs!

**Comment by GF-Huang** [comment]
Sorry, I don't understand the `IPEndPoint` you say. Is the local or remote or what ?

**Comment by mirasrael** [comment]
As I understand from code it asks Socks5 for bound endpoint. Then you send command for socks to redirect traffic from this bound endpoint to client's source endpoint, but client itself connects to bound endpoint. 
When client sends something to bound endpoint then this traffic will be redirected to remote endpoint and when remote server sends something back to Sock5 it redirects this traffic to source endpoint configured on previous step.
So if I will have bound endpoint then I can pass it to other UDP client which will can communicate with this bound endpoint just like if it communicate with remote server.

**Comment by GF-Huang** [comment]
After `UdpAssociate(Async)`method return, these fields will be set, they're returned by the socks server.
Is this what you need? 

![image](https://user-images.githubusercontent.com/4510984/52280875-cdbc9700-2997-11e9-8e7f-f37fa22ca919.png)

**Comment by mirasrael** [comment]
Yes, I don't want to have UdpClient created, instead I want to use my own UdpClient, but I need connection info for it. So this information will be enough to set up my own connection.

**Comment by mirasrael** [comment]
Basically
```csharp
// !!!! don't create it
            UDP = new UdpClient(srcPort, TCP.Client.AddressFamily);
            // !!!! fail if no srcPort provided
            if (srcPort == 0) 
                srcPort = ((IPEndPoint)UDP.Client.LocalEndPoint).Port;

            await SendCommandAsync(Command.UdpAssociate, _socksServerHost, _socksServerEndPoint.Address, srcPort);

            // !!! remove this part
            if (BoundType == AddressType.Domain)
                UDP.Connect(BoundDomain, BoundPort);
            else {
                // if BoundAddress is any (0.0.0.0 or ::), change it to socks server
                if (BoundAddress.Equals(IPAddress.Any) || BoundAddress.Equals(IPAddress.IPv6Any))
                    BoundAddress = _socksServerEndPoint?.Address ?? IPAddress.Parse(_socksServerHost);

                UDP.Connect(BoundAddress, BoundPort);
            }
```
Then after this call I can just use `BoundAddress` and `BoundPort` in my own client.

**Comment by GF-Huang** [comment]
You can use `Socklient.UDP` property to access the UdpClient after `UdpAssociate(Async)` method returned, but not support pass your custom `UdpClient` in it for construct `Socklient` instance currently.

**Comment by mirasrael** [comment]
Yes, I know, but I don't want to use `UdpClient` at all. I just want to have those Bound* properties set and pass it to third-party library (for direct socket connection without UpdClient at all). It shouldn't be too hard to add new method which will just prepare connection, but won't create `UdpClient`.

**Comment by GF-Huang** [comment]
So you need a `UdpAssociate(... ,UdpClient client, ...)` ?

**Comment by mirasrael** [comment]
No, as I said I don't have UpdClient at all. I need relay for Lidgren.Networking library. It creates plain `Socket` internally. And then I should just send unconnected messages to remote host. Don't even need to connect to this. So I need something like `UdpAssociate(... ,bool createClient = false, ...)`

**Comment by GF-Huang** [comment]
If you're developing a socks server scanner, I think you should copy the code of handshake for encapsulating your owner class will be better. 

Add a param for control whether or not create the `UdpClient`, it goes against the original intention of being easy to use.
